# backtest/engine.py
import pandas as pd
import numpy as np
import sys
import os
from config import config

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from database.db_handler import db
from ta_engine.indicators import TAEngine
from quant_engine.stats_models import QuantEngine
from smc_engine.structure import SMCEngine
from signal_engine.generator import SignalGenerator

class BacktestEngine:
    def __init__(self, initial_capital: float = 10000.0, risk_pct: float = 0.01):
        self.initial_capital = initial_capital
        self.risk_pct = risk_pct
        
    def calculate_max_drawdown(self, equity_curve: list) -> float:
        """Calculates the maximum peak-to-trough drop in the equity curve."""
        if not equity_curve:
            return 0.0
        peak = equity_curve[0]
        max_dd = 0.0
        for value in equity_curve:
            if value > peak:
                peak = value
            dd = (peak - value) / peak
            if dd > max_dd:
                max_dd = dd
        return max_dd * 100

    # Update the signature to pull from config
    def run(self, symbol: str, timeframe: str = '15m', rr_ratio: float = config.DEFAULT_RR_RATIO, min_confidence: int = config.MIN_CONFIDENCE_SCORE) -> dict:
        """Executes a vector-assisted historical backtest."""
        print(f"Initializing backtest for {symbol} on {timeframe} | RR: 1:{rr_ratio} | Conf{min_confidence}...")
        
        # 1. Fetch Historical Data  
        df = db.get_historical_data(symbol, timeframe, limit=500000)
        if df.empty:
            return {"error": "No historical data found. Run data sync first."}

        # 2. Apply Analytical Brain (Vectorized for speed)
        df = TAEngine.apply_all(df)
        df = QuantEngine.calculate_regime(df)
        df = SMCEngine.identify_fvgs(df)
        df = SMCEngine.map_structure(df)
        
        # Drop NaN values generated by rolling windows
        df.dropna(inplace=True)

        # 3. Simulation Variables
        capital = self.initial_capital
        equity_curve = [capital]
        trades = []
        generator = SignalGenerator()
        
        # Virtual position tracking
        open_trade = None

        for timestamp, row in df.iterrows():
            current_price = row['close']
            high = row['high']
            low = row['low']

            # --- 1. Manage Open Trades ---
            if open_trade:
                pnl = 0
                closed = False
                reason = ''

                if open_trade['direction'] == 'LONG':
                    # Realistic execution using High/Low wicks
                    if low <= open_trade['stop_loss']:
                        closed, reason = True, 'SL Hit'
                        pnl = (open_trade['stop_loss'] - open_trade['entry']) * open_trade['qty']
                    elif high >= open_trade['take_profit']:
                        closed, reason = True, 'TP Hit'
                        pnl = (open_trade['take_profit'] - open_trade['entry']) * open_trade['qty']

                else: # SHORT Logic
                    if high >= open_trade['stop_loss']:
                        closed, reason = True, 'SL Hit'
                        pnl = (open_trade['entry'] - open_trade['stop_loss']) * open_trade['qty']
                    elif low <= open_trade['take_profit']:
                        closed, reason = True, 'TP Hit'
                        pnl = (open_trade['entry'] - open_trade['take_profit']) * open_trade['qty']
                
                if closed:
                    capital += pnl
                    equity_curve.append(capital)
                    trades.append({
                        'entry_time': open_trade['entry_time'],
                        'exit_time': timestamp, 
                        'pnl': pnl, 
                        'reason': reason, 
                        'direction': open_trade['direction']
                    })
                    open_trade = None
                    
                    # ==========================================
                    # --- NEW: CAPITAL RECOVERY ALERT ---
                    # ==========================================
                    milestone_target = self.initial_capital * config.HOUSE_MONEY_MULTIPLIER
                    
                    # We use a flag to ensure it only alerts once per backtest/live run
                    if capital >= milestone_target and not getattr(self, 'milestone_hit', False):
                        print(f"\n🎉 [PORTFOLIO MILESTONE] Account equity reached ${round(capital, 2)}!")
                        print(f"💰 Safe to withdraw initial ${self.initial_capital}. You are now trading with House Money.\n")
                        self.milestone_hit = True # Prevent spamming the alert
                    # ==========================================
                continue

            # --- 2. Look for New Signals ---
            signal = generator.generate(symbol, row, mtf_alignment=True, rr_ratio=rr_ratio, min_confidence=min_confidence, candle_time=timestamp)
            
            if signal.get('status') == 'approved':
                risk_amount = capital * self.risk_pct
                price_dist = abs(signal['entry'] - signal['stop_loss'])
                qty = risk_amount / price_dist if price_dist > 0 else 0
                
                open_trade = {
                    'direction': signal['direction'],
                    'entry': signal['entry'],
                    'stop_loss': signal['stop_loss'],
                    'take_profit': signal['take_profit'],
                    'qty': qty,
                    'entry_time': timestamp
                }

        # 5. Generate Performance Metrics
        wins = [t for t in trades if t['pnl'] > 0]
        losses = [t for t in trades if t['pnl'] <= 0]
        
        win_rate = (len(wins) / len(trades)) * 100 if trades else 0
        gross_profit = sum([t['pnl'] for t in wins])
        gross_loss = abs(sum([t['pnl'] for t in losses]))
        profit_factor = (gross_profit / gross_loss) if gross_loss > 0 else float('inf')
        
        # --- NEW DEEP ANALYTICS ---
        # Force Pandas to parse the strings back into datetime objects
        start_date = pd.to_datetime(df.index[0])
        end_date = pd.to_datetime(df.index[-1])
        
        # Now the math will work perfectly
        total_days = max((end_date - start_date).days, 1)
        
        avg_win = (gross_profit / len(wins)) if wins else 0
        avg_loss = (gross_loss / len(losses)) if losses else 0
        
        # Format the trades list for the UI Data Table (returning the last 15 trades)
        formatted_trades = []
        for t in trades[-15:]:
            formatted_trades.append({
                # Force Pandas to parse the string back into a datetime object here
                "Date/Time": pd.to_datetime(t['exit_time']).strftime('%Y-%m-%d %H:%M'), 
                "Dir": t['direction'],
                "PnL": f"${round(t['pnl'], 2)}",
                "Exit": t['reason']
            })
        
        return {
            "symbol": symbol,
            "start_date": start_date.strftime('%Y-%m-%d'),
            "end_date": end_date.strftime('%Y-%m-%d'),
            "total_days": total_days,
            "total_trades": len(trades),
            "trades_per_day": round(len(trades) / total_days, 1),
            "win_rate": round(win_rate, 2),
            "profit_factor": round(profit_factor, 2),
            "avg_win": round(avg_win, 2),
            "avg_loss": round(avg_loss, 2),
            "max_drawdown": round(self.calculate_max_drawdown(equity_curve), 2),
            "net_profit": round(capital - self.initial_capital, 2),
            "final_equity": round(capital, 2),
            "equity_curve": equity_curve,
            "recent_trades": formatted_trades[::-1] # Reverse so newest is first
        }